from __future__ import annotations

from typing import Literal, Optional

import torch
import torch.nn as nn
from torch import Tensor

from .sde import LatentBridgeSDE


Direction = Literal["forward", "backward"]
InitialCoupling = Literal["paired", "independent"]


class MSBMCouplingSampler:
    """Coupling sampler for MSBM, faithfully mirroring ``MSBM/runner.py``.

    Data-anchoring mechanism (critical for IPF convergence):
        At every stage, **one endpoint of every training pair comes from the
        original data marginals** (``self.latent_traj``), while the other
        endpoint is generated by integrating the current importance policy.
        This anchors the bridge regression to the true marginals and prevents
        error accumulation across stages.

    Stage structure (mirrors ``MSBM/runner.py::sample_msbm_coupling``):
        Stage 1:
            Both endpoints come from data.  Default is paired coupling
            (same particle index across marginals — appropriate when the
            data represents tracked trajectories of the same physical samples).

        Stage > 1, direction="forward" (train backward, sample forward):
            - ``inits = data[:, :-1, :]``  (earlier marginals from DATA)
            - Forward policy rolls inits → transported endpoints ≈ later marginals
            - ``train_x0s = transported``, ``train_x1s = inits`` (DATA anchor)
            - Time labels FLIPPED for backward policy training

        Stage > 1, direction="backward" (train forward, sample backward):
            - ``inits = data[:, 1:, :]``  (later marginals from DATA)
            - Backward policy rolls inits → transported endpoints ≈ earlier marginals
            - ``train_x0s = transported``, ``train_x1s = inits`` (DATA anchor)
            - Time labels in forward order
    """

    def __init__(
        self,
        latent_trajectories: Tensor,  # (T, N, K)
        t_dists: Tensor,  # (T,)
        sde: LatentBridgeSDE,
        device: str,
        *,
        initial_coupling: InitialCoupling = "paired",
    ):
        if latent_trajectories.ndim != 3:
            raise ValueError(
                f"latent_trajectories must have shape (T, N, K); got {tuple(latent_trajectories.shape)}"
            )
        if t_dists.ndim != 1:
            raise ValueError(f"t_dists must have shape (T,); got {tuple(t_dists.shape)}")
        if latent_trajectories.shape[0] != t_dists.shape[0]:
            raise ValueError("latent_trajectories and t_dists must agree on the time dimension.")

        self.latent_traj = latent_trajectories.to(device)
        self.t_dists = t_dists.to(device)
        self.num_dist = int(t_dists.shape[0])
        self.num_samples = int(latent_trajectories.shape[1])
        self.sde = sde
        self.device = device
        if initial_coupling not in ("paired", "independent"):
            raise ValueError("initial_coupling must be 'paired' or 'independent'.")
        self.initial_coupling: InitialCoupling = initial_coupling

    def sample_coupling(
        self,
        *,
        stage: int,
        direction: Direction,
        policy_impt: Optional[nn.Module],
        batch_size: int,
        ts: Tensor,
        drift_clip_norm: Optional[float] = None,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Generate training pairs (y0, y1, t0, t1) for policy optimization.

        Returns:
            (y0, y1, t0, t1) where y1 is ALWAYS anchored to original data
            (for stage > 1) and y0 is the policy-transported endpoint.
            At stage 1, both endpoints come from data.
        """
        if stage <= 0:
            raise ValueError("stage must be >= 1.")
        if stage == 1:
            if self.initial_coupling == "paired":
                return self._paired_coupling(direction, batch_size)
            return self._independent_coupling(direction, batch_size)
        if policy_impt is None:
            raise ValueError("policy_impt must be provided for stage > 1.")
        return self._policy_coupling(direction, policy_impt, batch_size, ts, drift_clip_norm=drift_clip_norm)

    def _reverse_interval_idx(self, interval_idx: Tensor) -> Tensor:
        """Map forward interval indices to reversed-time interval indices.

        Mirrors ``MSBM/runner.py`` which flips ``train_t0s/train_t1s`` when
        training the backward policy.
        """
        num_intervals = self.num_dist - 1
        return (num_intervals - 1) - interval_idx

    def _paired_coupling(
        self,
        direction: Direction,
        batch_size: int,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Stage-1 paired coupling: same particle index across marginals.

        Appropriate when data represents tracked trajectories (same physical
        samples observed at different times / inclusion radii).
        """
        num_intervals = self.num_dist - 1
        interval_idx = torch.arange(num_intervals, device=self.device).repeat_interleave(batch_size)
        particle_idx = torch.randint(0, self.num_samples, (interval_idx.shape[0],), device=self.device)

        t0_f = self.t_dists[interval_idx]
        t1_f = self.t_dists[interval_idx + 1]

        rev_idx = self._reverse_interval_idx(interval_idx)
        t0_rev = self.t_dists[rev_idx]
        t1_rev = self.t_dists[rev_idx + 1]

        if direction == "forward":
            # Train backward: bridge from later → earlier (reversed time).
            # Both endpoints from DATA (paired — same particle across marginals).
            y0 = self.latent_traj[interval_idx + 1, particle_idx]  # DATA: later marginal
            y1 = self.latent_traj[interval_idx, particle_idx]      # DATA: earlier marginal
            t0, t1 = t0_rev, t1_rev
        else:
            # Train forward: bridge from earlier → later (forward time).
            # Both endpoints from DATA (paired).
            y0 = self.latent_traj[interval_idx, particle_idx]      # DATA: earlier marginal
            y1 = self.latent_traj[interval_idx + 1, particle_idx]  # DATA: later marginal
            t0, t1 = t0_f, t1_f

        return y0, y1, t0.unsqueeze(-1), t1.unsqueeze(-1)

    def _independent_coupling(
        self,
        direction: Direction,
        batch_size: int,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Stage-1 independent coupling — matches MSBM's default stage-1 behavior.

        Uses independently sampled particles at each marginal (different random
        indices for the two endpoints).
        """
        num_intervals = self.num_dist - 1
        interval_idx = torch.arange(num_intervals, device=self.device).repeat_interleave(batch_size)

        idx0 = torch.randint(0, self.num_samples, (interval_idx.shape[0],), device=self.device)
        idx1 = torch.randint(0, self.num_samples, (interval_idx.shape[0],), device=self.device)

        t0_f = self.t_dists[interval_idx]
        t1_f = self.t_dists[interval_idx + 1]

        rev_idx = self._reverse_interval_idx(interval_idx)
        t0_rev = self.t_dists[rev_idx]
        t1_rev = self.t_dists[rev_idx + 1]

        if direction == "forward":
            # Train backward: both endpoints from DATA (independently sampled).
            y0 = self.latent_traj[interval_idx + 1, idx0]  # DATA: later marginal
            y1 = self.latent_traj[interval_idx, idx1]       # DATA: earlier marginal
            t0, t1 = t0_rev, t1_rev
        else:
            # Train forward: both endpoints from DATA (independently sampled).
            y0 = self.latent_traj[interval_idx, idx0]       # DATA: earlier marginal
            y1 = self.latent_traj[interval_idx + 1, idx1]   # DATA: later marginal
            t0, t1 = t0_f, t1_f

        return y0, y1, t0.unsqueeze(-1), t1.unsqueeze(-1)

    def _policy_coupling(
        self,
        direction: Direction,
        policy_impt: nn.Module,
        batch_size: int,
        ts: Tensor,
        *,
        drift_clip_norm: Optional[float] = None,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """Stage > 1 policy-sampled coupling.

        Mirrors ``MSBM/runner.py::sample_msbm_coupling`` stages > 1:
        one endpoint is always from the ORIGINAL DATA (``latent_traj``),
        the other is generated by integrating the frozen importance policy.

        This data anchoring is the IPF correction mechanism that prevents
        error accumulation across stages.
        """
        num_intervals = self.num_dist - 1
        interval_idx = torch.arange(num_intervals, device=self.device).repeat_interleave(batch_size)
        particle_idx = torch.randint(0, self.num_samples, (interval_idx.shape[0],), device=self.device)

        t0_f = self.t_dists[interval_idx].unsqueeze(-1)
        t1_f = self.t_dists[interval_idx + 1].unsqueeze(-1)

        rev_idx = self._reverse_interval_idx(interval_idx)
        t0_rev = self.t_dists[rev_idx].unsqueeze(-1)
        t1_rev = self.t_dists[rev_idx + 1].unsqueeze(-1)

        if direction == "forward":
            # Train backward policy: sample endpoints by running frozen FORWARD policy.
            # Matches MSBM/runner.py:319-328 (direction="forward" block).
            #   inits = xs[:, :-1, :]          ← DATA from earlier marginals
            #   train_xs = sample_traj(z_f, inits, t0s)
            #   train_x0s = transported        ← policy-generated (≈ later marginals)
            #   train_x1s = inits              ← DATA (earlier marginals)
            y_data = self.latent_traj[interval_idx, particle_idx]  # DATA: earlier marginals
            _, y_transported = self.sde.sample_traj(
                ts,
                policy_impt,
                y_data,
                t0_f,
                save_traj=False,
                drift_clip_norm=drift_clip_norm,
                direction=getattr(policy_impt, "direction", "forward"),
            )

            # y0 = transported (≈ later marginals), y1 = DATA (earlier marginals)
            # Reversed time labels for backward policy training.
            y0 = y_transported
            y1 = y_data    # ← DATA ANCHOR (prevents error accumulation)
            t0 = t0_rev
            t1 = t1_rev

        else:
            # Train forward policy: sample endpoints by running frozen BACKWARD policy.
            # Matches MSBM/runner.py:311-317 (direction="backward" block).
            #   inits = xs[:, 1:, :]           ← DATA from later marginals
            #   train_xs = sample_traj(z_b, inits, t0s.flip())
            #   train_x0s = transported        ← policy-generated (≈ earlier marginals)
            #   train_x1s = inits              ← DATA (later marginals)
            y_data = self.latent_traj[interval_idx + 1, particle_idx]  # DATA: later marginals
            _, y_transported = self.sde.sample_traj(
                ts,
                policy_impt,
                y_data,
                t0_rev,
                save_traj=False,
                drift_clip_norm=drift_clip_norm,
                direction=getattr(policy_impt, "direction", "backward"),
            )

            # y0 = transported (≈ earlier marginals), y1 = DATA (later marginals)
            # Forward time labels for forward policy training.
            y0 = y_transported
            y1 = y_data    # ← DATA ANCHOR (prevents error accumulation)
            t0 = t0_f
            t1 = t1_f

        return y0, y1, t0, t1
